### ISSUE TITLE
Kanban Board Setup with Team

### ISSUE THREAD

**Issue by egichuhis** [AlselwiAisha/Ruby-Group-Capstone-Project#21]
Hello, please review this [Kanban Board](https://github.com/AlselwiAisha/Ruby-Group-Capstone-Project/projects/1) we have set up to help manage our project.

We are a team of 3 and we have assigned tasks as shown below: 

Team member 1 : @egichuhis
Team member 2: @HenaryKhuraijam 
Team member 3: @AlselwiAisha

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- TEAM work ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! Please add `description of the task` to some of the tasks because below the tasks haven't description 🙏🏼 
  - #5
  - #6
  - #7
  - #8
  - #10
  - #12
  - #14
  - #16
  - #18
  - #22
  - #29
  - #27 

- [ ] [REQUIRED] Good job so far!  Please assigned all team members to `group tasks` because I didn't see any of group tasks assigned all team members 🙏🏼 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omar-muhamad** [comment]
# Changes Required ♻️
### Hi Team,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Changes Required) Aspects to improve: ♻️

- [ ] There are 3 tasks that still need a description, Please make sure that all cards have a description as requested by the previous reviewer.

![image](https://github.com/AlselwiAisha/Ruby-Group-Capstone-Project/assets/68796232/07b7604b-533e-4188-a05e-0c8d8b058205)

![image](https://github.com/AlselwiAisha/Ruby-Group-Capstone-Project/assets/68796232/86a4b8f5-b2c0-40ca-b1c5-d5d58a7534cf)

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Shedrack-Sunday** [comment]
Hi @AlselwiAisha @HenaryKhuraijam @egichuhis       👍 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Kanban  features  ✔️  
- [x] Kudus on meeting the requirements as pointed the last time out   👏 


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
